### ISSUE TITLE
Error when treedecomposition has only 1 bag

### ISSUE THREAD

**Issue by gorczyca** [hmarkus/dp_on_dbs#7]
There seems to be an exception raised when the treedecomposition has only 1 bag (and hence no edges)

```
Traceback (most recent call last):
  File "/dp_on_dbs/dpdb.py", line 158, in <module>
    solve_problem(cfg,**vars(args))
  File "/dp_on_dbs/dpdb.py", line 81, in solve_problem
    td = TreeDecomp(tdr.num_bags, tdr.tree_width, tdr.num_orig_vertices, tdr.root, tdr.bags, tdr.adjacency_list)
  File "/dp_on_dbs/dpdb/treedecomp.py", line 34, in __init__
    add_nodes(root)
  File "/dp_on_dbs/dpdb/treedecomp.py", line 23, in add_nodes
    for a in adj[node]:
KeyError: 1
```

**Comment by hmarkus** [comment]
thx, fixed; was already resolved in branch nesthdb.
